language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: Test
      script: gradle test -i
    - stage: Release
      if: head_branch =~ ^release.*
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then gradle release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=$GITHUB_USER -Prelease.customPassword=$GITHUB_PASSWORD -s; fi'
    - stage: Bintray Upload
      if: head_branch =~ ^release.*
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then gradle bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PmavenCentralUser=$MAVEN_USER -PmavenCentralPassword=$MAVEN_PASSWORD; fi'
