language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: Build
      script: gradle test -i
    - stage: Release
      if: type != pull_request AND head_branch =~ ^release.*
      script:
        - 'gradle release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=$GITHUB_USER -Prelease.customPassword=$GITHUB_PASSWORD -s;'
    - stage: Bintray Upload
      if: type != pull_request AND head_branch =~ ^release.*
      script:
        - 'gradle bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PmavenCentralUser=$MAVEN_USER -PmavenCentralPassword=$MAVEN_PASSWORD;'
